"""
CDCL SAT Solver with Resolution Proof Production
Author: ZHANG Boyuan

Submission includes:
    cdcl.py (main implementation - required for submission)
    proof_checker.py (independent proof verifier)
    run_experiments.py (automated test suite)

This version on 'main' branch contains detailed internal comments and Chinese explanations 
for reference. The 'clean' branch contains the same logic but stripped of extra comments.
"""

import logging

# Create a logger for this module
logger = logging.getLogger(__name__)


class ProofLogger:
    """
    负责将分步归结过程记录到文件。
    记录格式: <new_id> <pivot> <id1> <id2> : <literals...> 0
    """
    def __init__(self, proof_file, n_initial):
        self._fh = open(proof_file, 'w', encoding='utf-8')
        # 写入注释头和维度信息
        self._fh.write("c Resolution proof generated by CDCL solver\n")
        self._fh.write("c Initial clause IDs: 1..%d\n" % n_initial)
        self._fh.write("p proof %d\n" % n_initial)

    def log_step(self, new_id, pivot, id1, id2, resolvent):
        """
        记录一步归结：new_id 是生成的子句ID，pivot 是消解文字，id1/id2 是父子句ID。
        """
        if resolvent:
            lits_str = ' '.join(str(l) for l in resolvent) + ' 0'
        else:
            lits_str = '0' # 空子句
        self._fh.write("%d %d %d %d : %s\n" % (new_id, pivot, id1, id2, lits_str))

    def close(self):
        self._fh.flush()
        self._fh.close()


class _NullLogger:
    """
    空日志器：当不需要生成证明时使用，避免在主循环中进行 if 判断，提高效率。
    """
    def log_step(self, *args, **kwargs):
        pass
    def close(self):
        pass


class CDCL:
    """ Assume the input is as follows:

    A list of clauses, each clause is a list of literals, each literal an integer, either positive or negative.

    All variables are named 1..n, a positive number is a positive literal, a negative number is a negative literal.
    """

    def __init__(self, clauses, proof_file=None):
        self.num_vars = 0
        for c in clauses:
            for i in c:
                if abs(i) > self.num_vars:
                    self.num_vars = abs(i)

        self.clauses = ClauseDb(self.num_vars, clauses)

        # Store the trail of assignments
        # Each element should be (lit, reason, level)
        self.trail = []

        # Current decision level
        self.decision_level = 0

        # Map of current VARIABLE assignment: {var: bool}
        self.assignments = {}

        # 初始化证明日志器
        n_initial = len(self.clauses.clauses)
        if proof_file is not None:
            self.proof = ProofLogger(proof_file, n_initial)
        else:
            self.proof = _NullLogger()


    def solve(self):
        """
        Main CDCL loop. 核心循环：Deduce -> Decide -> Analyze/Backtrack
        """
        logging.info("CDCL Search started")
        while (True):
            conflicting_clause = self.deduce()
            
            if conflicting_clause is None:
                # 无冲突：检查是否所有变量都已赋值
                if (self.all_assigned()):
                    logging.info("All literals assigned, SAT")
                    return True
                else:
                    # 还有未赋值变量：进行决策 (Decision)
                    self.decide()
            else:
                # 冲突检测：如果在决策层 0 发生冲突，说明公式 UNSAT
                if self.decision_level == 0:
                    conflict_id = self.clauses.clause_id.get(
                        id(conflicting_clause),
                        self._clause_id(conflicting_clause)
                    )
                    # 在退出前，补全到“空子句”的归结链
                    self._finish_proof_to_empty(conflicting_clause, conflict_id)
                    return False

                # 冲突分析：计算回溯层级和学习子句
                level, learned_clause = self.analyze(conflicting_clause)
                
                # 执行非时间顺序回溯
                self.backtrack(level)
                # 学习新子句并进入 BCP
                self.learn(learned_clause)

    def is_unit_clause(self, clause):
        """
        判断子句状态：已满足、单位子句、冲突或普通。
        """
        unassigned = []
        
        for lit in clause:
            var = abs(lit)
            if var in self.assignments: 
                var_value = self.assignments[var]
                lit_value = var_value if lit > 0 else not var_value
                if lit_value:  
                    return ("satisfied", None) # 子句已为真
            else:  
                unassigned.append(lit)
        
        if len(unassigned) == 0:
            return ("conflict", None) # 所有文字为假，冲突
        elif len(unassigned) == 1:
            return ("unit", unassigned[0]) # 只有一个文字未定，单位子句
        else:
            return ("normal", None) # 多个文字未定

    #TODO
    def deduce(self):
        """
        实现 BCP (Boolean Constraint Propagation)。
        不断寻找单位子句并进行传播。
        """
        logging.info("Deduce")
        while True:
            found_unit = False
            for c in self.clauses.clauses:
                status, lit = self.is_unit_clause(c)
                if status == "conflict":
                    logging.info("Conflict detected in clause %s" % c)
                    return c # 返回冲突子句
                elif status == "unit":
                    var = abs(lit)
                    value = (lit > 0)
                    logging.info("Unit propagation: %d from clause %s" % (lit, c))
                    self.assignments[var] = value
                    self.trail.append((lit, c, self.decision_level))
                    found_unit = True
                    break  
        
            if not found_unit:
                return None  # 无更多单位子句可传播
        
    def all_assigned(self):
        """
        Returns true if all the literals have been assigned.
        """
        return len(self.assignments) == self.num_vars
    
    #TODO
    def decide(self):
        """
        决策：选择一个新变量并赋值。
        """
        logging.info("Decide a new variable assignment")
        self.decision_level += 1
        for var in range(1, self.num_vars + 1):
            if var not in self.assignments:
                lit = var
                logging.info("Decision: variable %d = True at level %d" % (var, self.decision_level))
                self.assignments[var] = True
                self.trail.append((lit, None, self.decision_level)) # 决策的 reason 为 None
                return
        logging.warning("decide() called but all variables assigned")
    
    def resolve(self, clause1, clause2, lit):
        """
        归结 (Resolution) 两个子句。
        clause1 包含 -lit, clause2 包含 lit。
        """
        result = []
        for l in clause1:
            if l != -lit:
                result.append(l)
        for l in clause2:
            if l != lit and l not in result:
                result.append(l)
        return result

    def _clause_id(self, clause_list):
        """ 查找子句对应的证明 ID """
        key = tuple(sorted(clause_list))
        return self.clauses.content_to_id.get(key, 0)

    def _proof_resolve_step(self, conflict, current_id, lit, reason):
        """ 执行一步归结并记录证明 """
        reason_id  = self._clause_id(reason)
        new_id     = self.clauses.next_id
        self.clauses.next_id += 1
        
        new_clause = self.resolve(conflict, reason, lit)
        
        # 记录到文件
        self.proof.log_step(new_id, lit, current_id, reason_id, new_clause)
        # 注册新子句内容以便后续引用
        self.clauses.content_to_id[tuple(sorted(new_clause))] = new_id
        
        return new_clause, new_id

    #TODO
    def analyze(self, conflicting_clause):
        """
        1st-UIP 冲突分析。
        通过 trail 反向归结，直到冲突子句中只有一个文字属于当前决策层。
        """
        logging.info("Conflict analysis")
        
        if self.decision_level == 0:
            return 0, conflicting_clause
        
        lit_to_level = {}
        for trail_lit, reason, level in self.trail:
            lit_to_level[trail_lit]  = level
            lit_to_level[-trail_lit] = level
        
        current_id = self.clauses.clause_id.get(
            id(conflicting_clause),
            self._clause_id(conflicting_clause)
        )
        conflict = list(conflicting_clause)
        current_level_count = sum(1 for lit in conflict 
                                 if lit_to_level.get(lit, 0) == self.decision_level)
        
        # 从 trail 的顶端开始处理
        i = len(self.trail) - 1
        while current_level_count > 1:
            lit, reason, level = self.trail[i]
            # 如果 trail 中的文字的相反数在冲突子句中，进行归结
            if -lit in conflict and reason is not None:
                conflict, current_id = self._proof_resolve_step(
                    conflict, current_id, lit, reason
                )
                current_level_count = sum(1 for l in conflict 
                                         if lit_to_level.get(l, 0) == self.decision_level)
            i -= 1
        
        # 计算回溯层级 (第二高层级)
        levels = [lit_to_level.get(lit, 0) for lit in conflict]
        levels.sort(reverse=True)
        backtrack_level = levels[1] if len(levels) > 1 else 0
        
        logging.info("Learned clause: %s, backtrack to level %d" % (conflict, backtrack_level))
        return backtrack_level, conflict

    def _finish_proof_to_empty(self, conflict, current_id):
        """
        当在层级 0 冲突时，将当前冲突子句彻底归结为“空子句”。
        """
        working    = list(conflict)
        working_id = current_id
        lit_to_reason = {}
        for trail_lit, reason, level in self.trail:
            if reason is not None:
                lit_to_reason[-trail_lit] = reason
        
        changed = True
        while working and changed:
            changed = False
            i = 0
            while i < len(working):
                lit = working[i]
                reason = lit_to_reason.get(lit)
                if reason is not None:
                    pivot = -lit
                    working, working_id = self._proof_resolve_step(
                        working, working_id, pivot, reason
                    )
                    changed = True
                    i = 0 # 每次归结后重新扫描
                else:
                    i += 1

    #TODO
    def backtrack(self, level):
        """
        回溯到指定层级，撤销该层级之上的所有赋值。
        """
        while len(self.trail) > 0:
            lit, reason, dec_level = self.trail[-1]
            if dec_level <= level:
                break
            var = abs(lit)
            del self.assignments[var]
            self.trail.pop()
        self.decision_level = level

    #TODO
    def learn(self, clause):
        """
        记录学习到的冲突子句。
        """
        logging.info("Learning a new clause: %s" % clause)
        key = tuple(sorted(clause))
        pid = self.clauses.content_to_id.get(key, 0)
        # 建立对象 identity 到 ID 的映射，供 analyze 初期使用
        self.clauses.clause_id[id(clause)] = pid
        self.clauses.clauses.append(clause)


class ClauseDb:
    """
    Store the set of clauses. 
    """
    def __init__(self, num_vars, clauses):
        self.clauses = clauses
        self.unit = [] 
        self.lit2clauses = {}

        # 证明相关的映射表
        self.clause_id     = {} # {id(object): proof_id}
        self.content_to_id = {} # {tuple(sorted_lits): proof_id}
        self.next_id       = len(clauses) + 1

        # 初始化原始子句 ID：1 .. n
        for idx, c in enumerate(clauses):
            pid = idx + 1
            self.clause_id[id(c)]               = pid
            self.content_to_id[tuple(sorted(c))] = pid


def read_dimacs(filename):
    """
    Read a DIMACS CNF file and return the list of clauses.
    """
    clauses = []
    num_vars = 0
    num_clauses = 0

    with open(filename, 'r') as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith('c'):
                continue
            if line.startswith('p'):
                parts = line.split()
                if len(parts) >= 4 and parts[1] == 'cnf':
                    num_vars = int(parts[2])
                    num_clauses = int(parts[3])
                    continue
                else:
                    raise Exception("Malformed header %s" % line)

            # 解析子句
            literals = [int(x) for x in line.split() if int(x) != 0]
            clauses.append(literals)

    return clauses
