"""
CDCL implementation.

You should keep the interface of the constructor of the CDCL class and the method solve() in CDCL unchanged.

Otherwise, you are free to change any data structure as you wish (comments are appreciated)
"""

import logging

# Create a logger for this module
logger = logging.getLogger(__name__)


class ProofLogger:
    def __init__(self, proof_file, n_initial):
        self._fh = open(proof_file, 'w', encoding='utf-8')
        self._fh.write("c Resolution proof generated by CDCL solver\n")
        self._fh.write("c Initial clause IDs: 1..%d\n" % n_initial)
        self._fh.write("p proof %d\n" % n_initial)

    def log_step(self, new_id, pivot, id1, id2, resolvent):
        if resolvent:
            lits_str = ' '.join(str(l) for l in resolvent) + ' 0'
        else:
            lits_str = '0'
        self._fh.write("%d %d %d %d : %s\n" % (new_id, pivot, id1, id2, lits_str))

    def close(self):
        self._fh.flush()
        self._fh.close()


class _NullLogger:
    def log_step(self, *args, **kwargs):
        pass
    def close(self):
        pass


class CDCL:
    """ Assume the input is as follows:

    A list of clauses, each clause is a list of literals, each literal an integer, either positive or negative.

    All variables are named 1..n, a positive number is a positive literal, a negative number is a negative literal.
    """

    def __init__(self, clauses, proof_file=None):
        self.num_vars = 0
        for c in clauses:
            for i in c:
                if abs(i) > self.num_vars:
                    self.num_vars = abs(i)

        self.clauses = ClauseDb(self.num_vars, clauses)

        # Store the trail of assignments
        # Each element should be (lit, reason), with lit a literal 
        # and reason either None (for decisions) or a clause (for deductions)
        #
        # You will also need to store the decision level (either in the trail
        # directly or in another field)
        self.trail = []

        # Current decision level
        self.decision_level = 0

        # Map of current VARIABLE assignment, useful to evaluate a clause
        # Either contains a variable assigned to true or false, or does not when
        # the variable is unassigned
        # Should be kept in sync with decisions and deductions.
        self.assignments = {}

        n_initial = len(self.clauses.clauses)
        if proof_file is not None:
            self.proof = ProofLogger(proof_file, n_initial)
        else:
            self.proof = _NullLogger()


    def solve(self):
        """
        Main CDCL loop.

        Returns true if satisfiable, false if unsatisfiable
        """

        logging.info("CDCL Search started")
        while (True):
            conflicting_clause = self.deduce()
            
            if conflicting_clause is None:
                if (self.all_assigned()):
                    logging.info("All literals assigned, SAT")
                    return True
                else:
                    self.decide()
            else:
                if self.decision_level == 0:
                    conflict_id = self.clauses.clause_id.get(
                        id(conflicting_clause),
                        self._clause_id(conflicting_clause)
                    )
                    self._finish_proof_to_empty(conflicting_clause, conflict_id)
                    return False

                level, learned_clause = self.analyze(conflicting_clause)
                if (level == 0):
                    self.backtrack(0)
                    self.learn(learned_clause)
                else:
                    self.backtrack(level)
                    self.learn(learned_clause)

    def is_unit_clause(self, clause):
        """
        check if a clause is a unit clause
        return: (status, literal)
        - ("satisfied", None): SAT
        - ("unit", lit): unit clause, lit is the only unassigned literal
        - ("conflict", None): conflict (all literals are false)
        - ("normal", None): normal clause (multiple unassigned literals)
        """
        unassigned = []
        
        for lit in clause:
            var = abs(lit)
            if var in self.assignments: 
                var_value = self.assignments[var]
                lit_value = var_value if lit > 0 else not var_value
                if lit_value:  
                    return ("satisfied", None)  
            else:  
                unassigned.append(lit)
        
        if len(unassigned) == 0:
            return ("conflict", None)
        elif len(unassigned) == 1:
            return ("unit", unassigned[0])
        else:
            return ("normal", None) 

    #TODO
    def deduce(self):
        """
        Implement Boolean Constraint Propagation (BCP).

        Returns false if it detects a conflict, true otherwise.
        """
        logging.info("Deduce")
        while True:
            found_unit = False
            for c in self.clauses.clauses:
                status, lit = self.is_unit_clause(c)
                if status == "conflict":
                    logging.info("Conflict detected in clause %s" % c)
                    return c
                elif status == "unit":
                    var = abs(lit)
                    value = (lit > 0)
                    logging.info("Unit propagation: %d from clause %s" % (lit, c))
                    self.assignments[var] = value
                    self.trail.append((lit, c, self.decision_level))
                    found_unit = True
                    break  
        
            if not found_unit:
                return None  
        
    def all_assigned(self):
        """
        Returns true if all the literals have been assigned (you can use the self.assignments map)
        """
        return len(self.assignments) == self.num_vars
    
    #TODO
    def decide(self):
        """
        Select a new unassigned literal.

        Must update the trail, variable assignments, and decision level accordingly.
        """
        logging.info("Decide a new variable assignment")
        self.decision_level += 1
        for var in range(1, self.num_vars + 1):
            if var not in self.assignments:
                lit = var
                logging.info("Decision: variable %d = True at level %d" % (var, self.decision_level))
                self.assignments[var] = True
                self.trail.append((lit, None, self.decision_level))
                return
        logging.warning("decide() called but all variables assigned")
    
    def resolve(self, clause1, clause2, lit):
        """
        Resolute 2 clauses
        clause1 contains -lit, clause2 contains lit
        return resoluted clause
        """
        result = []
        for l in clause1:
            if l != -lit:
                result.append(l)
        for l in clause2:
            if l != lit and l not in result:
                result.append(l)
        return result

    def _clause_id(self, clause_list):
        key = tuple(sorted(clause_list))
        return self.clauses.content_to_id.get(key, 0)

    def _proof_resolve_step(self, conflict, current_id, lit, reason):
        reason_id  = self._clause_id(reason)
        new_id     = self.clauses.next_id
        self.clauses.next_id += 1
        new_clause = self.resolve(conflict, reason, lit)
        self.proof.log_step(new_id, lit, current_id, reason_id, new_clause)
        self.clauses.content_to_id[tuple(sorted(new_clause))] = new_id
        return new_clause, new_id

    #TODO
    def analyze(self, conflicting_clause):
        """
        Analyze the conflicting_clause using the trail.

        Returns the new level to backtrack to and a conflict clause.
        """
        logging.info("Conflict analysis")
        
        if self.decision_level == 0:
            return 0, conflicting_clause
        
        lit_to_level = {}
        for trail_lit, reason, level in self.trail:
            lit_to_level[trail_lit]  = level
            lit_to_level[-trail_lit] = level
        
        current_id = self.clauses.clause_id.get(
            id(conflicting_clause),
            self._clause_id(conflicting_clause)
        )
        conflict = list(conflicting_clause)
        current_level_count = sum(1 for lit in conflict 
                                 if lit_to_level.get(lit, 0) == self.decision_level)
        
        i = len(self.trail) - 1
        while current_level_count > 1:
            lit, reason, level = self.trail[i]
            if -lit in conflict and reason is not None:
                conflict, current_id = self._proof_resolve_step(
                    conflict, current_id, lit, reason
                )
                current_level_count = sum(1 for l in conflict 
                                         if lit_to_level.get(l, 0) == self.decision_level)
            i -= 1
        
        levels = [lit_to_level.get(lit, 0) for lit in conflict]
        levels.sort(reverse=True)
        backtrack_level = levels[1] if len(levels) > 1 else 0
        
        logging.info("Learned clause: %s, backtrack to level %d" % (conflict, backtrack_level))
        return backtrack_level, conflict

    def _finish_proof_to_empty(self, conflict, current_id):
        working    = list(conflict)
        working_id = current_id
        lit_to_reason = {}
        for trail_lit, reason, level in self.trail:
            if reason is not None:
                lit_to_reason[-trail_lit] = reason
        changed = True
        while working and changed:
            changed = False
            i = 0
            while i < len(working):
                lit = working[i]
                reason = lit_to_reason.get(lit)
                if reason is not None:
                    pivot = -lit
                    working, working_id = self._proof_resolve_step(
                        working, working_id, pivot, reason
                    )
                    changed = True
                    i = 0
                else:
                    i += 1

    #TODO
    def backtrack(self, level):
        """
        Undo the trail, assignments, and decision levels.

        Does not return a value.
        """
        while len(self.trail) > 0:
            lit, reason, dec_level = self.trail[-1]
            if dec_level <= level:
                break
            var = abs(lit)
            del self.assignments[var]
            self.trail.pop()
        self.decision_level = level

    #TODO
    def learn(self, clause):
        """
        Add a new clause to the set of clauses.

        Does not return a value.
        """
        logging.info("Learning a new clause: %s" % clause)
        key = tuple(sorted(clause))
        pid = self.clauses.content_to_id.get(key, 0)
        self.clauses.clause_id[id(clause)] = pid
        self.clauses.clauses.append(clause)


class ClauseDb:
    """
    Store the set of clauses Implement 2-watched literals
    """
    def __init__(self, num_vars, clauses):
        self.clauses = clauses
        # you may want to store the unit clauses
        # and use them only at decision level 0
        self.unit = [] 

        # Map from literal to the clauses containing it
        # This is just a suggestion, you can change this data structure as you wish.
        self.lit2clauses = {}

        self.clause_id     = {}
        self.content_to_id = {}
        self.next_id       = len(clauses) + 1

        for idx, c in enumerate(clauses):
            pid = idx + 1
            self.clause_id[id(c)]               = pid
            self.content_to_id[tuple(sorted(c))] = pid


def read_dimacs(filename):
    """
    Read a DIMACS CNF file and return the list of clauses.
    """
    clauses = []

    num_vars = 0
    num_clauses = 0

    with open(filename, 'r') as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            if line.startswith('c'):
                continue
            if line.startswith('p'):
                parts = line.split()
                if len(parts) >= 4 and parts[1] == 'cnf':
                    num_vars = int(parts[2])
                    num_clauses = int(parts[3])
                    continue
                else:
                    raise Exception("Malformed header %s" % line)

            # Parse clause line
            literals = []
            for x in line.split():
                lit = int(x)
                if lit != 0:
                    literals.append(lit)

            clauses.append(literals)

    return clauses
