"""
CDCL SAT Solver with Resolution Proof Production
Author: ZHANG Boyuan
Submission includes:
    cdcl.py (main implementation - required for submission)
    proof_checker.py (independent proof verifier)
    test_cdcl.py (automated test suite - optional)

Project 1 Extension:
    The solver optionally emits a resolution proof when solving UNSAT
    instances.  Enable by passing proof_file=<path> to CDCL.__init__().
    The original interface (CDCL(clauses).solve()) is fully preserved.

For complete project files and testing documentation, see:
https://github.com/FBI-openup/DAI-TD2-3.git

You should keep the interface of the constructor of the CDCL class and the 
method solve() in CDCL unchanged.
"""

import logging

# Create a logger for this module
logger = logging.getLogger(__name__)

# =============================================================================
# Proof Infrastructure
# =============================================================================
#
# Proof file format (plain text):
#
#   Header:
#     p proof <n>          -- n = number of initial clauses (IDs 1..n)
#
#   Each resolution step:
#     <new_id> <pivot> <id1> <id2> : <lit1> <lit2> ... 0
#
#   where:
#     new_id  -- ID assigned to the new resolvent clause
#     pivot   -- literal resolved away; id1 contains -pivot, id2 contains +pivot
#     id1     -- ID of parent clause containing -pivot
#     id2     -- ID of parent clause containing +pivot
#     lits 0  -- resolvent literals terminated by 0  ("0" alone = empty clause)
#
# =============================================================================

class ProofLogger:
    """Writes one resolution step per line to a plain-text proof file.

    When proof_file path is given, use a real ProofLogger.
    Otherwise use the lightweight _NullLogger (no-op).
    Two classes let the main logic stay branch-free.
    """

    def __init__(self, proof_file, n_initial):
        self._fh = open(proof_file, 'w', encoding='utf-8')
        # Header: record number of initial clauses so checker can identify them
        # ID 1..n_initial are initial; learned clauses start from n_initial+1
        self._fh.write("c Resolution proof generated by CDCL solver\n")
        self._fh.write("c Initial clause IDs: 1..%d\n" % n_initial)
        self._fh.write("p proof %d\n" % n_initial)

    def log_step(self, new_id, pivot, id1, id2, resolvent):
        """Record one resolution step.

        Args:
            new_id    : ID for the new resolvent clause
            pivot     : pivot literal (id1 has -pivot, id2 has +pivot)
            id1       : parent clause ID containing -pivot
            id2       : parent clause ID containing +pivot
            resolvent : list[int] forming the resolvent ([] means empty clause)
        """
        # Serialize resolvent: space-separated literals ending with 0 (DIMACS)
        # Empty resolvent [] encodes the empty clause -> just "0"
        if resolvent:
            lits_str = ' '.join(str(l) for l in resolvent) + ' 0'
        else:
            lits_str = '0'
        self._fh.write("%d %d %d %d : %s\n" % (new_id, pivot, id1, id2, lits_str))

    def close(self):
        self._fh.flush()
        self._fh.close()


class _NullLogger:
    """No-op proof logger used when proof output is disabled.
    Zero-cost sentinel so the main logic needs no if-branches.
    """
    def log_step(self, *args, **kwargs):
        pass
    def close(self):
        pass


# =============================================================================
# ClauseDb
# =============================================================================

class ClauseDb:
    """
    Store the set of clauses Implement 2-watched literals
    """
    def __init__(self, num_vars, clauses):
        self.clauses = clauses
        # you may want to store the unit clauses
        # and use them only at decision level 0
        self.unit = [] 

        # Map from literal to the clauses containing it
        # This is just a suggestion, you can change this data structure as you wish.
        self.lit2clauses = {}

        # -- Proof ID tables ---------------------------------------------------
        #
        # Two complementary maps so any clause can be looked up cheaply:
        #
        #   clause_id     : id(list_object) -> proof_id
        #     O(1) lookup by Python object identity.
        #     Used when deduce() returns the exact list object.
        #
        #   content_to_id : tuple(sorted(lits)) -> proof_id
        #     Content-based O(1) lookup.
        #     Used when we only have a reason list from the trail (and the
        #     list object identity may differ from the stored clause).
        #
        # Initial clause IDs: 1..n  (DIMACS order)
        # Learned clause IDs: allocated from next_id upward
        self.clause_id     = {}   # {id(list): int}
        self.content_to_id = {}   # {tuple(sorted_lits): int}
        self.next_id       = len(clauses) + 1   # next available proof ID

        # Register all initial clauses with IDs 1..n
        for idx, c in enumerate(clauses):
            pid = idx + 1
            self.clause_id[id(c)]               = pid
            self.content_to_id[tuple(sorted(c))] = pid


# =============================================================================
# CDCL Solver
# =============================================================================

class CDCL:
    """ Assume the input is as follows:

    A list of clauses, each clause is a list of literals, each literal an integer, either positive or negative.

    All variables are named 1..n, a positive number is a positive literal, a negative number is a negative literal.
    """

    def __init__(self, clauses, proof_file=None):
        """Initialize the CDCL solver.

        Args:
            clauses    : list of clauses in DIMACS integer-list format.
            proof_file : optional path to write the resolution proof.
                         Defaults to None (no proof, backward-compatible).
        """
        self.num_vars = 0
        for c in clauses:
            for i in c:
                if abs(i) > self.num_vars:
                    self.num_vars = abs(i)

        self.clauses = ClauseDb(self.num_vars, clauses)

        # Store the trail of assignments
        # Each element should be (lit, reason), with lit a literal 
        # and reason either None (for decisions) or a clause (for deductions)
        #
        # You will also need to store the decision level (either in the trail
        # directly or in another field)
        self.trail = [] # the trail of assignments list[Tuple[lit:int, reason:Clause, desision_level:int]]

        # Current decision level
        self.decision_level = 0

        # Map of current VARIABLE assignment, useful to evaluate a clause
        # Either contains a variable assigned to true or false, or does not when
        # the variable is unassigned
        # Should be kept in sync with decisions and deductions.
        self.assignments = {} # the dict of assignments {int: bool }

        # -- Proof logger setup ------------------------------------------------
        # Use real ProofLogger when proof_file is given, no-op otherwise.
        n_initial = len(self.clauses.clauses)
        if proof_file is not None:
            self.proof = ProofLogger(proof_file, n_initial)
        else:
            self.proof = _NullLogger()


    def solve(self):
        """
        Main CDCL loop.

        Returns true if satisfiable, false if unsatisfiable
        """

        logging.info("CDCL Search started")
        while (True):
            # MODIFIED: deduce() now returns None or conflicting clause
            conflicting_clause = self.deduce()
            
            if conflicting_clause is None:  # MODIFIED: check if no conflict
                if (self.all_assigned()):  # MODIFIED: fixed from self.trail.all_assigned()
                    logging.info("All literals assigned, SAT")
                    return True
                else:
                    self.decide()
            else:  # MODIFIED: conflict detected and returned
                if self.decision_level == 0:
                    # Conflict at level 0 with full BCP trail: derive empty clause for proof.
                    # At this point every trail entry has a reason clause (no decisions),
                    # so _finish_proof_to_empty can completely resolve down to empty.
                    conflict_id = self.clauses.clause_id.get(
                        id(conflicting_clause),
                        self._clause_id(conflicting_clause)
                    )
                    self._finish_proof_to_empty(conflicting_clause, conflict_id)
                    return False

                level, learned_clause = self.analyze(conflicting_clause) 
                if (level == 0):
                    # 1st-UIP determined UNSAT: learn the clause, backtrack to 0,
                    # then let the next iteration's deduce() find the real level-0
                    # conflict (all-BCP trail) and derive the empty clause there.
                    self.backtrack(0)
                    self.learn(learned_clause)
                else:
                    self.backtrack(level)
                    self.learn(learned_clause)
                    
    def is_unit_clause(self, clause):
        """
        check if a clause is a unit clause
        return: (status, literal)
        - ("satisfied", None): SAT
        - ("unit", lit): unit clause, lit is the only unassigned literal
        - ("conflict", None): conflict (all literals are false)
        - ("normal", None): normal clause (multiple unassigned literals)
        """
        unassigned = []
        
        for lit in clause:
            var = abs(lit)  # index of var
            if var in self.assignments: 
                var_value = self.assignments[var]  # (True/False)
                lit_value = var_value if lit > 0 else not var_value
                
                if lit_value:  
                    return ("satisfied", None)  
            else:  
                unassigned.append(lit)
        
        # Checked all literals
        if len(unassigned) == 0:
            return ("conflict", None)  # conflict
        elif len(unassigned) == 1:
            return ("unit", unassigned[0])  # unit clause
        else:
            return ("normal", None) 

    #TODO
    def deduce(self):
        """
        Implement Boolean Constraint Propagation (BCP).

        MODIFIED: Returns None if no conflict, otherwise returns the conflicting clause.
        """
        logging.info("Deduce")
        while True:
            found_unit = False
            for c in self.clauses.clauses:
                status, lit = self.is_unit_clause(c)
                if status == "conflict":
                    logging.info("Conflict detected in clause %s" % c)
                    return c  # MODIFIED: return conflicting clause instead of False
                elif status == "unit":
                    # unit propagation
                    var = abs(lit)
                    value = (lit > 0)
                    
                    logging.info("Unit propagation: %d from clause %s" % (lit, c))
                
                    self.assignments[var] = value
                    self.trail.append((lit, c, self.decision_level))
                
                    found_unit = True
                    break  
        
            if not found_unit:
                return None  # MODIFIED: return None instead of True  
        
    def all_assigned(self):
        """
        Returns true if all the literals have been assigned (you can use the self.assignments map)
        """
        return len(self.assignments) == self.num_vars
    
    #TODO
    def decide(self):
        """
        Select a new unassigned literal.

        Must update the trail, variable assignments, and decision level accordingly.
        """
        logging.info("Decide a new variable assignment")
        
        self.decision_level += 1
        
        # find a lit unassigned
        for var in range(1, self.num_vars + 1):
            if var not in self.assignments:
                lit = var  #decide positive literal = true
                
                logging.info("Decision: variable %d = True at level %d" % (var, self.decision_level))
                
                # update assignments and trail
                self.assignments[var] = True
                self.trail.append((lit, None, self.decision_level))  # reason=None means decided
                return
        # A secure print
        logging.warning("decide() called but all variables assigned,check solve() should have all assigned check")
    
    def resolve(self, clause1, clause2, lit):
        """
        Resolute 2 clauses
        clause1 contains -lit, clause2 contains lit
        return resoluted clause
        """
        result = []
        
        # add all literals from clause1 except -lit
        for l in clause1:
            if l != -lit:
                result.append(l)
        
        # add all literals from clause2 except lit (remove duplicates)
        for l in clause2:
            if l != lit and l not in result:
                result.append(l)
        
        return result

    def _clause_id(self, clause_list):
        """Look up proof ID of a clause by content (sorted-tuple key).
        Fallback to 0 if not registered.
        """
        key = tuple(sorted(clause_list))
        return self.clauses.content_to_id.get(key, 0)

    def _proof_resolve_step(self, conflict, current_id, lit, reason):
        """Helper: log one proof step and return (new_clause, new_id).

        Encapsulates the three actions that always go together:
          1. Determine parent IDs
          2. Log the step
          3. Register the new clause
          4. Return updated (conflict, id)

        This helper is called both from the 1st-UIP loop and from the
        extra pass that reduces the conflict to the empty clause.
        Every resolution step in the proof goes through here so the
        logic is in one place and easy to inspect.

        Parameters
        ----------
        conflict    : current working clause (list[int]) that contains -lit
        current_id  : proof ID of conflict
        lit         : pivot literal (reason contains +lit, conflict contains -lit)
        reason      : reason clause (list[int]) containing +lit
        """
        reason_id  = self._clause_id(reason)
        new_id     = self.clauses.next_id
        self.clauses.next_id += 1

        # pivot = lit: id1=current_id has -lit, id2=reason_id has +lit
        new_clause = self.resolve(conflict, reason, lit)

        self.proof.log_step(
            new_id    = new_id,
            pivot     = lit,
            id1       = current_id,
            id2       = reason_id,
            resolvent = new_clause,
        )

        # Register new clause in content map so later steps can look it up
        self.clauses.content_to_id[tuple(sorted(new_clause))] = new_id
        return new_clause, new_id

    #TODO
    def analyze(self, conflicting_clause):
        """
        Analyze the conflicting_clause using the trail.

        Returns the new level to backtrack to and a conflict clause.

        Project 1 Extension
        -------------------
        Every resolution step in the 1st-UIP derivation is logged via
        self.proof.log_step() (factored through _proof_resolve_step).

        Two special cases that need extra proof work:

        (A) decision_level == 0 from the start:
            All trail entries are BCP-forced (reason != None).
            We resolve the conflicting clause down to empty directly.

        (B) 1st-UIP produces a clause with only level-1 or higher literals,
            backtrack_level == 0, but the conflict is not yet empty.
            We run a second backward pass over the full trail to reduce
            the remaining literals to the empty clause.

        Both cases are handled by _finish_proof_to_empty() called after
        the normal 1st-UIP loop when we know we are returning (0, ...).
        """
        logging.info("Conflict analysis")
        
        # Note: decision_level == 0 case is now handled directly in solve() before
        # calling analyze(), so we should never reach here at level 0.
        # If we do (defensive), just return (0, conflicting_clause) with no proof step.
        if self.decision_level == 0:
            return 0, conflicting_clause
        
        # Build literal -> decision_level mapping in one trail pass
        lit_to_level = {}
        for trail_lit, reason, level in self.trail:
            lit_to_level[trail_lit]  = level
            lit_to_level[-trail_lit] = level
        
        # -- Proof: track the current working clause's ID ---------------------
        # Prefer object-identity lookup (deduce returns the exact list object)
        # then fall back to content-based lookup.
        current_id = self.clauses.clause_id.get(
            id(conflicting_clause),
            self._clause_id(conflicting_clause)
        )

        conflict = list(conflicting_clause)
        
        # Count literals at current decision level
        current_level_count = sum(1 for lit in conflict 
                                 if lit_to_level.get(lit, 0) == self.decision_level)
        
        # Backward traversal for 1st-UIP resolution
        # Stop when exactly one literal at the current decision level remains.
        i = len(self.trail) - 1
        while current_level_count > 1:
            lit, reason, level = self.trail[i]
            
            if -lit in conflict and reason is not None:
                conflict, current_id = self._proof_resolve_step(
                    conflict, current_id, lit, reason
                )
                # Recount literals at current level
                current_level_count = sum(1 for l in conflict 
                                         if lit_to_level.get(l, 0) == self.decision_level)
            
            i -= 1
        
        # Calculate backtrack level (second highest decision level in conflict)
        levels = [lit_to_level.get(lit, 0) for lit in conflict]
        levels.sort(reverse=True)
        backtrack_level = levels[1] if len(levels) > 1 else 0
        
        logging.info("Learned clause: %s, backtrack to level %d" % (conflict, backtrack_level))

        # When backtrack_level == 0 the proof empty-clause derivation happens
        # in solve() after BCP at level 0 produces a new all-BCP-trail conflict.
        # Nothing needed here.

        return backtrack_level, conflict

    def _finish_proof_to_empty(self, conflict, current_id):
        """Resolve all remaining literals in conflict to derive the empty clause.

        Used for UNSAT termination (backtrack_level == 0).  At this point
        the solver is about to return False, but the proof file needs a
        final step producing the empty clause.

        The literals in conflict were forced by BCP (reason != None) or
        by a decision later negated by a learned clause.  We scan the
        trail backward and resolve every literal we can.

        This function MODIFIES the clause database (adds intermediate IDs)
        but does NOT modify self.trail or self.assignments.

        Note: for decision literals (reason is None) the negation must come
        from an initial or learned unit clause.  We scan clauses for it.
        """
        working    = list(conflict)
        working_id = current_id

        # Build a quick-lookup map: literal -> reason clause for BCP entries
        # (only entries with a reason; decision entries have reason=None)
        lit_to_reason = {}
        for trail_lit, reason, level in self.trail:
            if reason is not None:
                # trail_lit is True, so its negation (-trail_lit) is False.
                # If conflict contains -trail_lit, we can resolve using reason.
                lit_to_reason[-trail_lit] = reason

        # Keep resolving until empty clause or no more progress
        changed = True
        while working and changed:
            changed = False
            i = 0
            while i < len(working):
                lit = working[i]
                reason = lit_to_reason.get(lit)
                if reason is not None:
                    # pivot = -lit (the trail assigned -lit as True, so reason has -lit)
                    # Actually: trail has trail_lit = -lit (True), reason clause forces -lit.
                    # resolve(conflict, reason, pivot) where pivot = -lit:
                    #   conflict has +lit (= -(-lit)), reason has -lit.
                    # Wait - let us be precise:
                    #   lit   is in working (False in current assignment)
                    #   -lit  is True (assigned by BCP from reason clause)
                    #   reason clause contains -lit among its literals
                    #   To resolve: pivot = -lit
                    #     id1 = working_id  (contains +(-lit) = lit? No...)
                    # Re-check sign convention in resolve():
                    #   resolve(clause1, clause2, lit):
                    #     clause1 contains -lit, clause2 contains +lit
                    # So for our case:
                    #   pivot_lit = -lit  (what the trail assigned as true)
                    #   clause1 (working) contains +pivot_lit? No, working has lit = -pivot_lit
                    #   clause2 (reason) should contain -pivot_lit? ...
                    #
                    # Let us re-derive carefully:
                    #   working contains the literal `lit` (which is False).
                    #   The trail contains trail entry (-(-lit) = ?)  -> trail has -lit absent
                    #   Actually: lit is False means trail assigned -lit := True.
                    #   trail_lit = -lit is True.
                    #   reason clause drove unit propagation of -lit (True).
                    #   reason contains -lit (the propagated literal).
                    #
                    #   Resolution on pivot p:
                    #     Remove  p from clause containing  p
                    #     Remove -p from clause containing -p
                    #     Union the rest.
                    #
                    #   pivot = lit  (working has -lit? No, working has +lit=lit)
                    #   Hmm: working contains `lit`.  We want to eliminate `lit`.
                    #   Resolution on pivot=lit eliminates lit from id1 and -lit from id2.
                    #   clause1 (id1) must contain -pivot = -lit   -> NO, working has +lit
                    #   clause2 (id2) must contain  pivot =  lit   -> working has lit, ok
                    #
                    #   Swap: pivot = -lit
                    #   clause1 must contain -(-lit) = lit  -> working has lit, OK
                    #   clause2 must contain  (-lit)        -> reason has -lit, OK
                    #
                    # Therefore: pivot = -lit, id1 = working, id2 = reason
                    pivot = -lit   # the literal to resolve away
                    working, working_id = self._proof_resolve_step(
                        working, working_id, pivot, reason
                    )
                    changed = True
                    i = 0   # restart from beginning
                else:
                    i += 1

    #TODO
    def backtrack(self,level):
        """
        Undo the trail, assignments, and decision levels.

        Does not return a value.
        """
        while len(self.trail) > 0:
            lit, reason, dec_level = self.trail[-1]
            
            if dec_level <= level:
                break  #skip the lit satisfies
            # delete assignments
            var = abs(lit)
            del self.assignments[var]
            # delete trail tail (-1)
            self.trail.pop()# equal to pop(-1)
        self.decision_level = level

    #TODO
    def learn(self, clause):
        """
        Add a new clause to the set of clauses.

        Does not return a value.

        Project 1 Extension:
            We register the new clause in clause_id by object identity
            so deduce() can look it up later when the clause triggers a conflict.
        """
        logging.info("Learning a new clause: %s" % clause)

        # Register by object identity: deduce() returns the list object,
        # and we need to map id(list) -> proof_id for future conflict analysis.
        key    = tuple(sorted(clause))
        pid    = self.clauses.content_to_id.get(key, 0)
        self.clauses.clause_id[id(clause)] = pid

        # MODIFIED: self.clauses is ClauseDb object, need to access .clauses list
        self.clauses.clauses.append(clause)


# =============================================================================
# DIMACS Reader
# =============================================================================

def read_dimacs(filename):
    """
    Read a DIMACS CNF file and return the list of clauses.
    """
    clauses = []

    num_vars = 0
    num_clauses = 0

    with open(filename, 'r') as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            if line.startswith('c'):
                continue
            if line.startswith('p'):
                parts = line.split()
                if len(parts) >= 4 and parts[1] == 'cnf':
                    num_vars = int(parts[2])
                    num_clauses = int(parts[3])
                    continue
                else:
                    raise Exception("Malformed header %s" % line)

            # Parse clause line
            literals = []
            for x in line.split():
                lit = int(x)
                if lit != 0:
                    literals.append(lit)

            clauses.append(literals)

    return clauses
